### PR TITLE
New gradient background for "No image available."

### PR DESCRIPTION
**Pull request by kfogel**

### CODE REVIEW

**Comment by reefdog** [comment]
@kfogel Well, discovered a flow issue here on GitHub.

I couldn't merge in your PR because it was out of date with `main`, so I used GitHub's interface support for doing a rebase from `main` — which worked! Except it means the rebase commit is no longer signed by _you_, which conflicts with one of our (very good) rules. Clearly I should have [RTFM](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#signature-verification-for-rebase-and-merge).

Could I ask you re-apply your commit to a fresh `main` locally, and then either force-push to this branch or just close the PR and open a new one? (I prefer the former, but am not picky.)

Sorry for the trouble.

**Comment by kfogel** [comment]
@reefdog Will do right now, sure.  One sec.

**Comment by kfogel** [comment]
Please try it now, @reefdog.

**Comment by reefdog** [comment]
@kfogel Huh… I can see that you force-pushed a Solo Karl Fogel Commit™, but it doesn't appear to be signed — which we (now? newly?) require, therefore merging is blocked.

Are you setup to sign your Git commits?

**Review by hminsky2002 — APPROVED** [review]
This is a nicer image! Approved

**Comment by kfogel** [comment]
> @kfogel Huh… I can see that you force-pushed a Solo Karl Fogel Commit™, but it doesn't appear to be signed — which we (now? newly?) require, therefore merging is blocked.
> 
> Are you setup to sign your Git commits?

@reefdog I asked this [elsewhere](https://chat.opentechstrategies.com/#narrow/stream/80-Public-Access/topic/development/near/199574), but since this is the original place I'll ask here too:

1) Sign with GPG key or SSH key, or either is fine?
2) Is the commit-signing requirement documented somewhere?  (Hint: it's *not* documented in this repository...)

I'm happy to set this up; I'd just like to make sure I do it right.

**Comment by reefdog** [comment]
> 1. Sign with GPG key or SSH key, or either is fine?

Either!

> 2. Is the commit-signing requirement documented somewhere?  (Hint: it's _not_ documented in this repository...)

It's not… and it should be! I just added #68 to capture the issue.

In the interim, I think @hminsky2002 released the requirement, so we can temporarily trust you are you and merge this in.

**Pull request merged**
