### PR TITLE
Polish detail page

### LINKED ISSUE #87: Polish the layout of resource detail pages
The Figma design (which doesn't take all current feedback into account yet — so consider this a rough target):

Artwork page

### PR DESCRIPTION
**Pull request by reefdog**
- Improve layout of detail page
- Improve usability of buttons by giving them all borders (no more "raw text buttons")
- Improve consistency of link display/interactivity

Closes #87

### CODE REVIEW

**Comment by reefdog** [comment]
Whoops, I forgot to Lint/Prettify. Will edit commits and re-push.

**Review by hminsky2002 — CHANGES_REQUESTED** [review]
Pinch me, i'm screaming (aaaa). This looks so great, thank you @reefdog . The only request I have, and this is something we should start doing regularly until we develop a different way of serving the application, is to commit the latest built assets as part of this PR (and all prs moving forward). This just involves running the `npm run build`. command and committing the outputted assets that are then loaded into `archesdataviewer/static`.

**Comment by reefdog** [comment]
@hminsky2002 Done and done!

**Review by hminsky2002 — APPROVED** [review]
We're building like minecraft. Woohoo!

**Pull request merged**
